name        : ruby
version     : 2.2.3
release     : 5
source      :
    - https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.gz : df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
homepage    : http://www.ruby-lang.org
license     :
    - Ruby
summary     : dynamic, reflexive, object-oriented language
description : |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    autoreconf -vfi
    %configure --disable-rpath \
                         --enable-shared \
                         --enable-pthread\
                         --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
