name       : ruby
version    : 2.3.7
release    : 14
source     :
    - http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.7.tar.xz : c61f8f2b9d3ffff5567e186421fa191f0d5e7c2b189b426bb84498825d548edb
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
