name       : ruby
version    : 3.2.2
release    : 27
source     :
    - https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz : 96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc
homepage   : https://www.ruby-lang.org
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto.
builddeps  :
    - pkgconfig(yaml-0.1)
    - pkgconfig(libxcrypt)
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
