name       : ruby
version    : 2.3.5
release    : 10
source     :
    - https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.5.tar.gz : 5462f7bbb28beff5da7441968471ed922f964db1abdce82b8860608acc23ddcc
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %patch -p1 < $pkgfiles/configure-2.3.5.diff
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
