name       : ruby
version    : 2.2.6
release    : 8
source     :
    - https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.6.tar.gz : de8e192791cb157d610c48a9a9ff6e7f19d67ce86052feae62b82e3682cc675f
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --enable-pthread\
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
