name       : ruby
version    : 2.6.5
release    : 16
source     :
    - https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.xz : d5d6da717fd48524596f9b78ac5a2eeb9691753da5c06923a6c31190abe01a62
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
