name       : ruby
version    : 3.0.4
release    : 23
source     :
    - https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.4.tar.gz : 70b47c207af04bce9acea262308fb42893d3e244f39a4abc586920a1c723722b
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
