name       : ruby
version    : 2.2.5
release    : 7
source     :
    - https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.xz : f86feaa0a578e8da0924ced3ec68b25b50d69fc9a72cc8d919bc3c73f85f87d7
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --enable-pthread\
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
