name       : ruby
version    : 3.0.3
release    : 21
source     :
    - https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz : 3586861cb2df56970287f0fd83f274bd92058872d830d15570b36def7f1a92ac
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
