name       : ruby
version    : 3.1.4
release    : 26
source     :
    - https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz : a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6
homepage   : https://www.ruby-lang.org
license    : Ruby
component  : programming
summary    : dynamic, reflexive, object-oriented language
description: |
    Ruby is a dynamic, reflexive, object-oriented programming language that blends parts of Perl, Smalltalk, Eiffel, Ada, and Lisp to create a language that balanced functional and imperative programming. It was created by Yukihiro "matz" Matsumoto.
builddeps  :
    - pkgconfig(libxcrypt)
setup      : |
    %reconfigure --disable-rpath \
        --enable-shared \
        --with-sitedir=/usr/lib/ruby/site_ruby
build      : |
    %make
install    : |
    %make_install
